import Navbar from "./components/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import NavbarData from "@/app/Utils/data/navbarData.json";
import SidebarData from "@/app/Utils/data/sidebarData.json";
import Sidebar from "./components/Sidebar/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar navbarItems={NavbarData} />
        <Sidebar sidebarItmes={SidebarData} />
        {children}
      </body>
    </html>
  );
}
