import NavbarData from "@/app/Utils/data/navbarData.json";
import SidebarData from "@/app/Utils/data/sidebarData.json";
import { Inter } from "next/font/google";

import Navbar from "./components/Navbar/Navbar";
import Sidebar from "./components/Sidebar/Sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row h-screen">
          <Sidebar sidebarItmes={SidebarData} />
          <div className="w-full">
            <Navbar navbarItems={NavbarData} />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
