#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

npm run format || (
    echo "\n❌ Prettier Check Failed.❌\n Please run 'npm run format', add the changes, and try committing again.👀 \n"
    false
)

npm run check-format || (
    echo "\n❌ Prettier Check Failed.❌\n Please run 'npm run format', add the changes, and try committing again.👀 \n"
    false
)

echo "✅ Commit Hook Passed! Committing changes now. 💪\n"